shinyUI(fluidPage(theme="yeti.css",
                  shinyjs::useShinyjs(),
                  div(
                    id = "loading_page",
                    h1("Loading...")
                  ),
                  hidden(
                    div(
                      id = "main_content",
                      # suppress error messages as data loads, hacky
                      tags$style(type="text/css",
                                 ".shiny-output-error { visibility: hidden; }",
                                 ".shiny-output-error:before { visibility: hidden; }"
                      ),
                      navbarPage(paste("VDEQ ",assessmentCycle," IR Riverine Assessment Tool", sep=''),
#                                 tabPanel('Data Upload',
#                                          h3('Tool Overview'),
#                                          p("The Riverine Assessment Tool is designed to expedite analysis, assessment
#                                            decisions, and quality assurance/quality control (QA/QC) procedures for Virginia's
#                                            2022 Integrated Report (IR). The data window analyzed covers 
#                                            January 1, 2015 to December 31, 2020. Users can expect significant time savings
#                                            on repetitive procedures including: raw data organization from disparate databases, 
#                                            geospatial organization of stations by assessment unit, standard/criteria calculations, 
#                                            and data visualization."),
#                                          p('This application represents the second iteration of an automated assessment tool. The datasets
#                                            and parameters chosen for analysis readily lend themselves to automated processing. Future versions
#                                            of the tool may include additional datasets and analyses.'),
#                                          p('For feedback, troubleshooting, and questions regarding analyses or missing data, please contact 
#                                            Emma Jones (emma.jones@deq.virginia.gov)'),
#                                          br(),
#                                          h3('Tool Inputs'),br(),
#                                          h4('Prepopulated Tool Inputs'),
#                                          p("Some data sources are compiled for users and programmed into the app, requiring no user manipulation.
#                                            These datasets include: "),
#                                          tags$ul(
#                                            tags$li('Conventionals- CEDS data pulled and analyzed by Roger Stewart (roger.stewart@deq.virginia.gov) for each 
#                                            Integrated Report data window.'), 
#                                            tags$li('Water Column and Sediment Metals- CEDS data pulled, filtered, and analyzed by Roger Stewart for each 
#                                            Integrated Report data window.'), 
#                                            tags$li("Statewide Assessment (spatial) layer- The spatial dataset that identifies each regional office's watersheds."),
#                                            tags$li("CEDS EDAS- Statewide macroinvertebrate data and stream condition indices are pulled and organized from the 
#                                            Integrated Report data window. Contact Jason Hill (jason.hill@deq.virginia.gov) or your regional
#                                                    biologist with dataset questions.")  ),
#                                          br(),
#                                          h4('User Defined Tool Inputs'),
#                                          p('In order to allow for more flexible assessment unit updates as required throughout the assessment process,
#                                             users must upload certain datasets that follow a specified template. These include their regional
#                                             Stations Table (generated by the automated assessment scripts) and Regional Assessment Unit shapefiles.'),
#                                          h5('Stations Table- Generated by the Automated Assessment Tool'),
#                                          helpText('This dataset is derived before any Riverine Assessment Tool analysis 
#                                                   procedures can commence using information provided by assessors from the ',
#                                                   span(strong('Regional Assessment Metadata Validation Tool.')), 
#                                                   'After completing the necessary WQS and AU attribution steps overviewed in the ',
#                                                   span(strong('Regional Assessment Metadata Validation Tool')),'once, users are provided
#                                                   an initial automated assessment (Stations Table) to upload to this application and/or
#                                                   the ',span(strong('CEDS WQA Stations Table Bulk Upload')), ' tool. Should any assessment 
#                                                   units change throughout the assessment process, users have the ability to update their local
#                                                   Stations Table and Regional Assessment Units spatial layers with the required changes and 
#                                                   upload those new datasets to this application. With that updated information, this tool will
#                                                   reflect the changes to the user. This process may be repeated as many times as is necessary 
#                                                   throughout the assessment process. After stations and AUs are reviewed, users may upload
#                                                   their Stations Table to the ', span(strong('CEDS WQA Stations Table Bulk Upload')), ' tool.'),
#                                          helpText(strong('A note on Inversioning spatial data: '),"If assessment unit changes are necessary throughout
#                                                   the course of the assessment process, the user should update their local AU spatial dataset, sync 
#                                                   these changes to the statewide spatial datasest, and export a local copy of this updated spatial
#                                                   dataset for use in the assessment applications. Users should also alter the assessment unit name
#                                                   attributed to the station(s) in the Station Table to ensure the assessment applications can appropriately
#                                                   reorganize data according to the user's changes."),
#                                          fileInput('stationsTable','Upload your Regional Stations Table.',
#                                                    accept = c(".csv")),
#                                          h5('Regional Assessment Units'),
#                                          helpText(span('This shapefile is the current working copy of the regional assessment units.',
#                                                        strong('It will be uploaded to the app on startup for you to avoid shiny application 
#                                                           data upload limits.'), ' Any time any spatial changes (performed in ArcGIS on
#                                                   the file soured by the application) to the assessment units (e.g. split an assessment 
#                                                   unit) are saved', strong('and the application is re-launched'), 'these changes will be
#                                                   reflected in the Riverine Assessment Tool.')),
#                                          h6(strong('To view or change the location of the Regional Assessment Units shapefile sourced
#                                                    by the application, see the AUshapefileLocation.R script.'))
#                                          #fileInput('regionalAUshapefile','Choose your Regional Assessment Unit shapefile.',
#                                          #          accept = c(".shp",#)),# only need .shp for st_read 
#                                          #                     ".dbf",".prj",".sbn",".sbx","shp.xml",".shx"), multiple = T),
#                                 ),
                                 tabPanel('Watershed Selection',
                                          sidebarPanel(
                                            helpText("Select Region to Assess and click ",span(strong("Retrieve Assessment Units From Server")), "button
                                                     to bring in spatial data for further analyses."),
                                            uiOutput('DEQregionSelectionUI'),
                                            #dynamicSelectInput("DEQregionSelection", "Select DEQ Assessment Region", multiple = FALSE),
                                            br(),
                                            actionButton('pullAUs',"Retrieve Assessment Units From Server",class='btn-block'),
                                            br(),
                                            dynamicSelectInput("basinSelection", "Select Basin/Subbasin", multiple = FALSE),
                                            dynamicSelectInput("HUC6Selection", "Select VAHU6", multiple = FALSE),
                                            br(),
                                            
                                            #actionButton('reviewAUs',"Preview Assessment Units",class='btn-block')
                                            ),
                                          mainPanel(
                                            verbatimTextOutput('test'),
                                            leafletOutput('VAmap'),
                                            br(),
                                            h5(strong('Assessment Units in Selected VAHU6')),
                                            DT::dataTableOutput('AUSummary'),
                                            h5(strong('Stations in Selected VAHU6 that were sampled in current window')),
                                            helpText("The stations highlighted in gray can be analyzed by the application. The stations
                                                     highlighted in yellow were sampled in the current window, but cannot be analyzed by the
                                                     application because they are not in the input stations table 2.0"),
                                            DT::dataTableOutput('stationSummary'),
                                            
                                            br(), br(), br() # a bit of breathing room
                                          )
                                 )
                      )))))
                                            