shinyUI(fluidPage(theme="yeti.css",
                  shinyjs::useShinyjs(),
                  div(
                    id = "loading_page",
                    h1("Loading...")
                  ),
                  hidden(
                    div(
                      id = "main_content",
                      # suppress error messages as data loads, hacky
                      tags$style(type="text/css",
                                 ".shiny-output-error { visibility: hidden; }",
                                 ".shiny-output-error:before { visibility: hidden; }"
                      ),
                      navbarPage(paste("VDEQ ",assessmentCycle," IR Riverine Assessment Tool", sep=''),
                                 # add back in
                                 tabPanel('Data Upload',
                                          h3('Tool Overview'),
                                          p("The Riverine Assessment Tool is designed to expedite analysis, assessment
                                            decisions, and quality assurance/quality control (QA/QC) procedures for Virginia's
                                            2022 Integrated Report (IR). The data window analyzed covers 
                                            January 1, 2015 to December 31, 2020. Users can expect significant time savings
                                            on repetitive procedures including: raw data organization from disparate databases, 
                                            geospatial organization of stations by assessment unit, standard/criteria calculations, 
                                            and data visualization."),
                                          p('This application represents the second iteration of an automated assessment tool. The datasets
                                            and parameters chosen for analysis readily lend themselves to automated processing. Future versions
                                            of the tool may include additional datasets and analyses.'),
                                          p('For feedback, troubleshooting, and questions regarding analyses or missing data, please contact 
                                            Emma Jones (emma.jones@deq.virginia.gov)'),
                                          br(),
                                          h3('Tool Inputs'),br(),
                                          h4('Prepopulated Tool Inputs'),
                                          p("Some data sources are compiled for users and programmed into the app, requiring no user manipulation.
                                            These datasets include: "),
                                          tags$ul(
                                            tags$li('Conventionals- CEDS data pulled and analyzed by Roger Stewart (roger.stewart@deq.virginia.gov) for each 
                                            Integrated Report data window.'), 
                                            tags$li('Water Column and Sediment Metals- CEDS data pulled, filtered, and analyzed by Roger Stewart for each 
                                            Integrated Report data window.'), 
                                            tags$li("Statewide Assessment (spatial) layer- The spatial dataset that identifies each regional office's watersheds."),
                                            tags$li("CEDS EDAS- Statewide macroinvertebrate data and stream condition indices are pulled and organized from the 
                                            Integrated Report data window. Contact Jason Hill (jason.hill@deq.virginia.gov) or your regional
                                                    biologist with dataset questions.")  ),
                                          br(),
                                          h4('User Defined Tool Inputs'),
                                          p('In order to allow for more flexible assessment unit updates as required throughout the assessment process,
                                             users must upload certain datasets that follow a specified template. These include their regional
                                             Stations Table (generated by the automated assessment scripts) and Regional Assessment Unit shapefiles.'),
                                          h5('Stations Table- Generated by the Automated Assessment Tool'),
                                          helpText('This dataset is derived before any Riverine Assessment Tool analysis 
                                                   procedures can commence using information provided by assessors from the ',
                                                   span(strong('Regional Assessment Metadata Validation Tool.')), 
                                                   'After completing the necessary WQS and AU attribution steps overviewed in the ',
                                                   span(strong('Regional Assessment Metadata Validation Tool')),'once, users are provided
                                                   an initial automated assessment (Stations Table) to upload to this application and/or
                                                   the ',span(strong('CEDS WQA Stations Table Bulk Upload')), ' tool. Should any assessment 
                                                   units change throughout the assessment process, users have the ability to update their local
                                                   Stations Table and Regional Assessment Units spatial layers with the required changes and 
                                                   upload those new datasets to this application. With that updated information, this tool will
                                                   reflect the changes to the user. This process may be repeated as many times as is necessary 
                                                   throughout the assessment process. After stations and AUs are reviewed, users may upload
                                                   their Stations Table to the ', span(strong('CEDS WQA Stations Table Bulk Upload')), ' tool.'),
                                          helpText(strong('A note on Inversioning spatial data: '),"If assessment unit changes are necessary throughout
                                                   the course of the assessment process, the user should update their local AU spatial dataset, sync 
                                                   these changes to the statewide spatial datasest, and export a local copy of this updated spatial
                                                   dataset for use in the assessment applications. Users should also alter the assessment unit name
                                                   attributed to the station(s) in the Station Table to ensure the assessment applications can appropriately
                                                   reorganize data according to the user's changes."),
                                          fileInput('stationsTable','Upload your Regional Stations Table.',
                                                    accept = c(".csv")),
                                          h5('Regional Assessment Units'),
                                          helpText(span('This shapefile is the current working copy of the regional assessment units.',
                                                        strong('It will be uploaded to the app on startup for you to expedite application rendering
                                                        time.'), ' Any changes to the regional dataset (e.g. split an assessment 
                                                        unit) should be synced with the statewide version and a copy of the ', strong('new spatial 
                                                        dataset should be sent to Emma Jones (emma.jones@deq.virginia.gov) to update on the server.')))
                                          #h6(strong('To view or change the location of the Regional Assessment Units shapefile sourced
                                          #          by the application, see the AUshapefileLocation.R script.'))
                                          #fileInput('regionalAUshapefile','Choose your Regional Assessment Unit shapefile.',
                                          #          accept = c(".shp",#)),# only need .shp for st_read 
                                          #                     ".dbf",".prj",".sbn",".sbx","shp.xml",".shx"), multiple = T),
                                 ),
                                 
                                 
                                 tabPanel('Watershed Selection',
                                          sidebarPanel(
                                            p('Run once per user session.'),
                                            helpText("Select Region to Assess and click ",span(strong("Retrieve Assessment Units From Server")), "button
                                                     to bring in spatial data for further analyses."),
                                            uiOutput('DEQregionSelectionUI'),
                                            br(),
                                            actionButton('pullAUs',"Retrieve Assessment Units From Server",class='btn-block'),
                                            hr(),
                                            p('Run as often as necessary per user session.'),
                                            dynamicSelectInput("basinSelection", "Select Basin/Subbasin", multiple = FALSE),
                                            dynamicSelectInput("HUC6Selection", "Select VAHU6", multiple = FALSE),
                                            helpText('To begin assessing the selected VAHU6, click the ',
                                                     span(strong('Assessment Unit Review')), ' tab at the top of the navigation bar.'),
                                            hr(),
                                            p('Optional.'),
                                            helpText('After you use the VAHU6 drop down to select your desired watershed, you may
                                                     preview the stations and AUs contained within the selected watershed by clicking the ',
                                                     span(strong('Spatially Preview Stations and Assessment Units')),' below.'),
                                            actionButton('reviewAUs',"Spatially Preview Stations and Assessment Units",class='btn-block')
                                          ),
                                          mainPanel(
                                            leafletOutput('VAmap'),
                                            br(),
                                            h5(strong('Assessment Units in Selected VAHU6')),
                                            DT::dataTableOutput('AUSummary'),
                                            br(),
                                            h5(strong('Stations in Selected VAHU6 that were sampled in current window')),
                                            helpText("The stations highlighted in gray can be analyzed by the application. The stations
                                                     highlighted in yellow were sampled in the current window, but cannot be analyzed by the
                                                     application because they are not in the input stations table."),
                                            DT::dataTableOutput('stationSummary'),
                                            br(),
                                            h5(strong("Stations in Selected VAHU6 that have no data in the current window but were carried 
                                                      over from last cycle due to an IM designation in one of the 2020IR status fields.")),
                                            helpText('These stations can be viewed in the application and stations table, but none of the 
                                                     parameter modules will display data as no data is available in the current window.'),
                                            DT::dataTableOutput('carryoverStationSummary'),
                                            
                                            br(), br(), br() # a bit of breathing room
                                          )
                                 ),
                                 
                                 tabPanel('Assessment Unit Review',
                                          #fluidRow(column(9, 
                                          DT::dataTableOutput('selectedVAHU6'),#)),#,
                                          #column(3,br(),actionButton('pullVAHU6data','Select Watershed for analysis'),
                                          #      helpText('If the button above is disabled, there are no AUs in the selected VAHU6 watershed.'))),
                                          hr(),
                                          uiOutput('AUselection_'),
                                          h5(strong('AU information from last cycle')),
                                          DT::dataTableOutput('selectedAU'),br(),
                                          uiOutput('stationSelection_'),
                                          fluidRow(column(4, DT::dataTableOutput('stationInfo')),
                                                   column(4, leafletOutput('stationMap', height = 300, width = 300),
                                                          helpText("The AUs displayed on the map above represent all AUs associated with the selected
                                                                  station (listed in a station's ID305B_1:ID305B_10 fields) for context. ")),
                                                   column(4, 
                                                          tabsetPanel(
                                                            tabPanel('2020 Station Table',
                                                                     DT::dataTableOutput('stationHistoricalInfo1')),
                                                            tabPanel('2018 Station Table',
                                                                     DT::dataTableOutput('stationHistoricalInfo2'))))),
                                          hr(),
                                          h3('Station Results for Review'),
                                          helpText('This table outputs the site specific results for direct export to the Station Table. It also serves to highlight
                                                  where exceedances are present and should be reviewed in the individual parameter visualization tabs below.'),
                                          h4('Stations Table Results'),
                                          helpText('Parameters are highlighted
                                                  in different colors to indicate further review may be necessary. Parameters highlighted in yellow have at least one 
                                                  violation of a standard. When BENTHIC_STAT is highlighed, it indicates there is benthic data present for that site
                                                  and the assessor should review that information with the Regional Biologist. Parameters highlighted in red exceed the 10.5% exceedance rate. Both scenarios warrant further
                                                  investigation and may requre comments in the Station Table and ADB.'),
                                          h5(strong('If no station table appears, then there is no data within the assessment window for the selected station.'), 
                                             'Please investigate the Historical Station Information table above for information as to why this station is
                                             included in the application.'),
                                          DT::dataTableOutput('stationTableDataSummary'), br(),
                                          h4('PWS violations'),
                                          helpText("Any PWS violations should noted in a station's COMMENT field of the Stations Table. The table below organizes 
                                                  PWS information to expedite the comment process."),
                                          DT::dataTableOutput('PWStable'),
                                          br(),hr(),br(),
                                          h3('Assessment Unit Raw Data Review and Visualization'),
                                          tabsetPanel(
                                            tabPanel('Conventionals Data',
                                                     tabsetPanel(
                                                       tabPanel('Raw Data',br(),
                                                                DT::dataTableOutput('AURawData'),
                                                                h4('Data Summary'),
                                                                h5('Records Retrieved in Assessment Unit:'),
                                                                fluidRow(column(1),column(10,textOutput('stationDataTableRecords'))),
                                                                h5('Field and Lab Data in Assessment Window:'),
                                                                fluidRow(column(1),column(10,tableOutput('uniqueStationDataTableRecords'))),
                                                                h5('Assessment Window:'),
                                                                fluidRow(column(1),column(10,textOutput('stationDataTableAssessmentWindow'))), br(),br()),
                                                       tabPanel('Temperature',
                                                                helpText('Review each site using the single site visualization section. The results from this analysis are reflected
                                                                        in the TEMP_EXC, TEMP_SAMP, and TEMP_STAT columns in the station table.',
                                                                         span('Users may adjust the WQS used for analysis in this modal by choosing a standard from
                                                                              the `WQS for Analysis` drop down. The default WQS chosen is the WQS provided by the assessor
                                                                              to the WQS Metadata Attribution App.', style="color:red")),
                                                                temperaturePlotlySingleStationUI('temperature')),
                                                       tabPanel('pH',
                                                                helpText('Review each site using the single site visualization section. The results from this analysis are reflected
                                                                        in the PH_EXC, PH_SAMP, and PH_STAT columns in the station table.',
                                                                         span('Users may adjust the WQS used for analysis in this modal by choosing a standard from
                                                                              the `WQS for Analysis` drop down. The default WQS chosen is the WQS provided by the assessor
                                                                              to the WQS Metadata Attribution App.', style="color:red"),
                                                                         'The Benthic Stressor Analysis background colors are provided as a guide to users, but all analyses are conducted against the chosen WQS.'),
                                                                pHPlotlySingleStationUI('pH')),
                                                       tabPanel("DO",
                                                                helpText('Review each site using the single site visualization section. The results from this analysis are reflected
                                                                        in the DO_EXC, DO_SAMP, and DO_STAT columns in the station table.',
                                                                         span('Users may adjust the WQS used for analysis in this modal by choosing a standard from
                                                                              the `WQS for Analysis` drop down. The default WQS chosen is the WQS provided by the assessor
                                                                              to the WQS Metadata Attribution App.', style="color:red"),
                                                                         'The Benthic Stressor Analysis background colors are provided as a guide to users, but all analyses are conducted against the chosen WQS.'),
                                                                DOPlotlySingleStationUI('DO')),
                                                       tabPanel("Specific Conductance",
                                                                helpText('Review each site using the single site visualization section. There are no WQS for Specific Conductivity.'),
                                                                SpCondPlotlySingleStationUI('SpCond')),
                                                       tabPanel("Salinity", 
                                                                helpText('Review each site using the single site visualization section. There are no WQS for Salinity.'),
                                                                salinityPlotlySingleStationUI('salinity')),
                                                       tabPanel("Total Nitrogen",
                                                                helpText('Review each site using the single site visualization section. There are no WQS for Total Nitrogen.'),
                                                                TNPlotlySingleStationUI('TN')),
                                                       tabPanel("Ammonia",
                                                                br(), h4('Hang tight, module still in development.'), br(), br(), br(), br(), br(), br()),
                                                       tabPanel("Total Phosphorus",
                                                                helpText('Review each site using the single site visualization section. There are no WQS for Total Nitrogen.'),
                                                                TPPlotlySingleStationUI('TP')),
                                                       tabPanel("Fecal Coliform",
                                                                helpText('Review each site using the single site visualization section. There are no WQS for Fecal Coliform.'),
                                                                fecalPlotlySingleStationUI('fecal')),
                                                       tabPanel("E. Coli",
                                                                #verbatimTextOutput('testOutside'),
                                                                helpText('Review each site using the single site visualization section. Both the old and the new E. coli assessment
                                                                        methods are presented in the station visualization section. The results from the new analysis method are reflected
                                                                        in the ECOLI_EXC, ECOLI_SAMP, ECOLI_GM_EXC, ECOLI_GM_SAMP, and ECOLI_STAT columns in the station table.'),
                                                                EcoliPlotlySingleStationUI('Ecoli')),
                                                       tabPanel("Enterococci",
                                                                #verbatimTextOutput('testOutside'),
                                                                helpText('Review each site using the single site visualization section. Both the old and the new E. coli assessment
                                                                        methods are presented in the station visualization section. The results from the new analysis method are reflected
                                                                        in the ENTER_EXC, ENTER_SAMP, ENTER_GM_EXC, ENTER_GM_SAMP, and ENTER_STAT columns in the station table.'),
                                                                EnteroPlotlySingleStationUI('Entero')),
                                                       tabPanel("Chlorophyll a",
                                                                helpText('Review each site using the single site visualization section. There are no WQS for Chlorophyll a.'),
                                                                chlAPlotlySingleStationUI('chlA')),
                                                       tabPanel("Suspended Sediments",
                                                                helpText('Review each site using the single site visualization section. There are no WQS for Suspended Sediments.'),
                                                                SSCPlotlySingleStationUI('SSC')),
                                                       tabPanel("Nitrate",
                                                                helpText('Review each site using the single site visualization section. Nitrate criteria only apply to stations with PWS designation.'),
                                                                NitratePlotlySingleStationUI('Nitrate')),
                                                       tabPanel("Chloride",
                                                                helpText('Review each site using the single site visualization section. Chloride criteria only apply to stations with PWS designation.'),
                                                                NitratePlotlySingleStationUI('Cl')),
                                                       tabPanel("Sulfate",
                                                                helpText('Review each site using the single site visualization section. Total Sulfate criteria only apply to stations with PWS designation.'),
                                                                DSulfatePlotlySingleStationUI('DSulfate'))
                                                     )),
                                            tabPanel('EDAS Data',
                                                     br(), h4('Hang tight, module still in development.'), br(), br(), br(), br(), br(), br()),
                                            tabPanel('Metals Data',
                                                     helpText('Review each site using the single site visualization section. All analyses were performed outside of the
                                                              automated assessment scripts, so please direct questions to Roger Stewart (roger.stewart@deq.virginia.gov).'),
                                                     metalsTableSingleStationUI('metals')),
                                            tabPanel('Toxics Data', 
                                                      tabsetPanel(
                                                        tabPanel('Fish Tissue Data',
                                                                 br(), h4('Hang tight, module still in development.'), br(), br(), br(), br(), br(), br()),
                                                        tabPanel('Water Column Toxics',
                                                                 br(), h4('Hang tight, module still in development.'), br(), br(), br(), br(), br(), br()),
                                                        tabPanel('Sediment Toxics',
                                                                 br(), h4('Hang tight, module still in development.'), br(), br(), br(), br(), br(), br())))
                                            
                                          ))        
                                          
                                 )))))